### ISSUE TITLE
Does this deal with callback?

### ISSUE THREAD

**Issue by dnwk** [gr2m/cloudflare-worker-github-oauth-login#10]
Does this deal with oauth callbacks?
I am trying to do oauth for netlify cms

example: https://github.com/vencax/netlify-cms-github-oauth-provider

**Comment by gr2m** [comment]
Not right now, but it could be added. I’m not familiar with what the netlify CMS is though

**Comment by dnwk** [comment]
Ok. netlify cms is CMS for Hugo static site. I am working through a way to pass that oauth callback info back to it.

**Comment by gr2m** [comment]
If you receive the code from Githubs OAuth callback, you can send a POST request to your Cloudflare worker with the code and you will receive the token in return.
