### ISSUE TITLE
Relicensed fork?

### ISSUE THREAD

**Issue by whinee** [gr2m/cloudflare-worker-github-oauth-login#13]
Hello, I really like your project, so so much that I forked it to make it as the base of my application.

I, however found a problem:
I want to eventually merge my derivative of your project to [another repo](https://github.com/whinee/cf-worker) of mine which in turn is also a derivative of two repos, though they are MIT-licensed. Now, this is will cause a license conflict, despite ISC license being closely related to MIT. Can I relicense my fork from ISC license to MIT? I will still properly attribute you, the only thing that will change is the license.

Thank you for your consideration and have a good day!

**Comment by whinee** [comment]
Hello. After doing some research, I have found out that it is generally agreed upon that the derived works of an ISC-licensed project can not be re-licensed, but the changes someone made to that derivative can be licensed under a new license. Now, it is not stated if there are licenses which this "rule" can not apply to. However, quoting some stuff that I got from the internet, since MIT license is so closely related to ISC license, this "rule" applies.

For now, I will make it so that the changes I've done on my derivative will be licensed under MIT and the license agreement will be written on `docs/LICENSE.md`, while everything that I've got from this repository will still be licensed under ISC and the license agreement will be written on `docs/NOTICE.md`. I will also indicate that my derivative is not properly licensed, but is at all my might. I really find this project really helpful, and I want to attribute you, the author of this very useful project, properly.

This issue will not be closed though, as I still want to hear your thoughts about this. Thank you so much!

Links:
- https://opensource.stackexchange.com/questions/12454/can-any-project-under-isc-have-the-license-migrated-to-mit-text-by-me-if-it-poss
- https://www.quora.com/Can-an-ISC-license-be-changed-to-MIT-since-the-MIT-license-essentially-contains-ISC-permissions-inside-it-Therefore-meeting-the-criteria?share=1

**Comment by gr2m** [comment]
I'm no license expert, if it's as simple as permitting you to re-license the work code to MIT for your case, I have no problem with that at all. Whatever is simplest for you

**Comment by ArjixWasTaken** [comment]
licensing really do be weird, so much legalese that only gives headaches
and in the end, it really depends on what country you are in, since the license has to be accepted by that country's courts in order to protect the code

**Comment by whinee** [comment]
> ...if it's as simple as permitting you to re-license the work code to MIT for your case, I have no problem with that at all. Whatever is simplest for you

OMG, thank you so so much.

> licensing really do be weird, so much legalese that only gives headaches

Can not agree more. But in this case, I just want to properly attribute the author of this project.

I will now close this issue. Again, thank you so much, and have a good day!
