### ISSUE TITLE
Redirect back from github resulted in endless redirect back to github

### ISSUE THREAD

**Issue by AlexMikhalev** [gr2m/cloudflare-worker-github-oauth-login#14]
Hello, Gregor (@gr2m), thank you for the project: I was looking for a walkthrough GitHub auth. 
I tried to follow README and deployed the app on my pages, currently authorisation work on GitHub but then trigger endless redirect between GitHub and worker URL. 
Is anything specific about worker URL in callback on Github? 
I put worker URL in Callback `https://github-oauth-login.terraphim.workers.dev/`

**Comment by gr2m** [comment]
The worker URL should only be called directly for initial login. Afterwards you should send a `POST` request to the worker with the code, and retrieve the access token in response. Your GitHub OAuth App should redirect to your website/app, not the worker, otherwise you end up in the infinite loop.

**Comment by AlexMikhalev** [comment]
Thank you for the clarification - I will need to write that API endpoint.
