### ISSUE TITLE
Host through a Worker vs. GitHub Pages

### ISSUE THREAD

**Issue by brentrealbt** [gr2m/cloudflare-worker-github-oauth-login#6]
Instead of using GitHub Pages, I'd simply like to host through a Worker. Trying to think through the logic (if there is anything that wouldn't work properly?)

**Comment by gr2m** [comment]
I don't see a problem with hosting both your static HTML and the OAuth Web Flow backend in the same CloudFlare worker. It is, however, out of scope for this package. 

Would love to see a minimal example though, I'd be happy to link it from the README.

I'll close the issue as there is nothing actionable for me to do, but please feel free to comment
