### ISSUE TITLE
User-Agent header missing

### ISSUE THREAD

**Issue by xtuc** [gr2m/cloudflare-worker-github-oauth-login#7]
That probably changed since this template was created. User-Agent seems to be required by the GitHub API now.

Full message
```
"\r\nRequest forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.\r\n"
```
returned by tthe call to `https://api.github.com/user`

**Comment by gr2m** [comment]
Hmm `@octokit` always sets the `User-Agent` header by default. Could you share a reproducible test case?

**Comment by xtuc** [comment]
I'm using the worker that doesn't use @octokit

**Comment by gr2m** [comment]
Ah I see, sorry, it's been a while since I looked at the code. We will have to add the user agent header here: 
https://github.com/gr2m/cloudflare-worker-github-oauth-login/blob/998fe6d9d03c029712166d65ead09b93b5e0775d/github-oauth-login.js#L33-L43

would you like to send a PR?
